# docker-compose.yml

# 主要分成三个部分： 服务器、客户端、管理端 （每一个部分现在一个）
# 服务器： 1. go-server； 2. go-servers; 3. spring-server
# 客户端： 1. vue-client; 2. react-client
# 管理端： 1. vue-admin; 2. react-admin
services:
  go-server:
  # go-servers:
  # spring-server:

  vue-client:
  # react-client:

  vue-admin:
  # react-admin:
