# public container of project sharing
services:
  redis:
    image: redis:7-alpine
    container_name: dev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - network
      - mikufus

  postgres:
    image: postgres:16
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data/data:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d # 默认运行 sql script
    networks:
      - network
      - mikufus

  minio:
    image: minio/minio
    container_name: dev-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/var/lib/minio
    networks:
      - network
      - mikufus

networks:
  network:
    driver: bridge
  mikufus:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  minio_data:
